### PR TITLE
moved Markdownhelp to projectmanagement folder

### PR DESCRIPTION
**Pull request by jeremywalter**
these changes have are connected to the welcome-to-cfde PR (coming up next)

### CODE REVIEW

**Comment by jeremywalter** [comment]
https://github.com/nih-cfde/welcome-to-cfde/pull/36

**Comment by jeremywalter** [comment]
seems unnecessary

**Comment by jeremywalter** [comment]
these look useful for finishing up #46

**Comment by jeremywalter** [comment]
I lost track of this PR and got a little confused, but it seems like the finishing touch on updating the project management folder.

**Review by ACharbonneau — APPROVED** [review]

**Pull request merged**
