### PR TITLE
Add Onboarding readthedocs

### PR DESCRIPTION
**Pull request by josesanchez1815**
Instructions for how to add members to readthedocs.com for business

### CODE REVIEW

**Comment by ACharbonneau** [comment]
Hey there. I had originally intended for this to live in the dib-lab onboarding, since we own all the RTD websites, but there's no reason this can't live in this repo. However if it's going to live here, and be part of normal, overall onboarding, it needs to be linked into the onboarding process somehow, and there needs to be info about how to decide if someone gets added.

**Comment by josesanchez1815** [comment]
We can leave this out until there is a need for it. I thought this might belong here as it pertains to onboarding. But since we own all the RTDs, I'm ok with this document just staying in the DIB lab cfde repo

**Comment by jeremywalter** [comment]
Soo... I won't approve this for merge because we're gonna maybe keep it in house??

**Comment by josesanchez1815** [comment]
Yes we will just keep in house for now.

**Pull request closed without merging**
