### PR TITLE
Change Format on custom message for mailing list

### PR DESCRIPTION
**Pull request by jeremywalter**
previous version was not copy/pasteable in groups.io
added links and punctuation

### CODE REVIEW

**Comment by jeremywalter** [comment]
nudge

**Comment by jeremywalter** [comment]
ping ping ping... please make onboarding easier by approving me so copy pasting works

**Review by ACharbonneau — DISMISSED** [review]

**Comment by ACharbonneau** [comment]
you changed the markdown formatting around the text from ``` to --- and that makes it so it isn't going to copy out right at all I think...are you sure this is what you want?

**Comment by jeremywalter** [comment]
I did do that on purpose because it copy pastes as a chunk that has to be scrolled sideways to edit...

**Review by ACharbonneau — APPROVED** [review]
k. the links aren't going to copy out right tho i think. but if it works for you, it's fine

**Pull request merged**
