### PR TITLE
fix mailto for Code of Conduct

### PR DESCRIPTION
**Pull request by jeremywalter**

### CODE REVIEW

**Comment by jeremywalter** [comment]
> lgtm

neat, can you approve? ;)

**Comment by abhijna** [comment]
so I approved this a couple of times but it didn't go through. Has someone revoked my approving previleges?

**Comment by abhijna** [comment]
i did the approving when i commented on Friday. don't know what's happening.

**Comment by josesanchez1815** [comment]
Maybe you didn't have written access to this repo?

**Comment by josesanchez1815** [comment]
I saw that and the PR didn't allow me to merge, so I tried to contact Amanda .

**Comment by josesanchez1815** [comment]
I'll see what I can do on my end.

**Pull request closed without merging**
