### PR TITLE
Orgorg

### PR DESCRIPTION
**Pull request by jeremywalter**
first go at reorganizing org:
added projectmanagement sub dir and moved pm related things to the readme there -- linked in the org readme

### CODE REVIEW

**Comment by ACharbonneau** [comment]
you seem to have lost the off boarding link. It should be right at the top with onboarding. Otherwise this looks fine.

**Comment by jeremywalter** [comment]
Do you mean the offboarding form in the Personnel section under Program Management? Do you want it out front on the org page as well?

**Comment by ACharbonneau** [comment]
on front page, with onboarding please. It can be in both places if you like tho

**Review by ACharbonneau — DISMISSED** [review]

**Comment by jeremywalter** [comment]
I ruined your approval by adding more commits. I'm terrible.

**Review by ACharbonneau — APPROVED** [review]

**Pull request merged**
