### PR TITLE
GitHub Guide instructions

### PR DESCRIPTION
**Pull request by cmball1**
Added steps and screenshots for items in the Table of Contents in the `GitHubUsage.md`.

PR is in reference to https://github.com/dib-lab/CFDE_Engage/issues/20

### CODE REVIEW

**Comment by cmball1** [comment]
@fridayek Thanks for your review, it's very helpful. Here are the updates I made, can you check over them?
* Turn Definitions section into a table
* Alphabetize Definitions section
* Referencing Pull Requests section: The list once you enter `#` has both Pull Requests and Issues. I tried to update the language here to reflect that. Hopefully it's more clear.
* Closing Pull Requests section: I updated the text here.
* Forking a Repository and Creating a New Repository Branch sections are now before the Pull Requests section.
* New Repository Branch section: The images were in the wrong order. I also changed the word button to be more descriptive.

**Comment by fridayek** [comment]
The changes look great! Thank you! I really like the table of definitions, but I think it might look better left justified instead of centered. What do you think?

**Comment by cmball1** [comment]
@fridayek I think you are right. I pushed a change to left justify the table. Thanks for your help.

**Comment by cmball1** [comment]
@ACharbonneau This is ready for your review/approval.

**Pull request merged**
