### PR TITLE
cross-reference with Master Contact

### PR DESCRIPTION
**Pull request by jeremywalter**
Went through Master Contact list and added PIs and PMs not listed

### CODE REVIEW

**Comment by ACharbonneau** [comment]
Edits:

- Carol Place is not in Sansone group
- We don't know who the PM for Kids First is. Those people should all get taken off
- Robin is the PM for HuBMAP, the other people aren't
- You have the admin contacts in places that don't make sense to me. How would I know that to get ahold of Katy I need to contact Matthew? Same for Danay and Owen, etc
- Ian Foster doesn't need himself as an admin contact
- Rick doesn't actually work for Foster anymore...I'm leaning towards leaving him there because he does still kind of PM for Foster, but that is not his current email
- I don't understand the order of people in each category. I think it would be easiest if all the PIs (for instance) were either in order by 'inchargeness' or alphabetically.  GTEx and HuBMAP have the main PIs first, but 4D is alphabetical. KF is neither. Alphabetical is probably easiest for reference.

**Comment by jeremywalter** [comment]
On Mon, Nov 2, 2020 at 3:36 PM Amanda Charbonneau <notifications@github.com>
wrote:

> Edits:
>
>    - Carol Place is not in Sansone group --
>    - We don't know who the PM for Kids First is. Those people should all
>    get taken off <-- these people all onboarded as PMs
>
> Michelle Mattioni (Senior Program Manager)
Maia Nguyen (Project Manager)
Denis Beauregard (Project Manager)
Tatiana Patton was entered as Project Manager on the Master List (they
have not onboarded)


>
>    - Robin is the PM for HuBMAP, the other people aren't
>
> Margaret Vella (Project Manager)
Elizabeth Record (Project Manager)
John Graybeal (not onboarded... job description is Technical Program
Manager / has been active in CP)

>
>    - You have the admin contacts in places that don't make sense to me.
>    How would I know that to get ahold of Katy I need to contact Matthew? Same
>    for Danay and Owen, etc
>
> Admin Contact is totally nebulous, but I thought it made sense to you...
it doesn't tell me it's for one person. I will try a fix...

**Comment by josesanchez1815** [comment]
Hi! I apologize. I'm the one who labeled some of the people under Kids First as project managers and they are also labeled that way in the master contact list. I did that because they labeled themselves as such in the [Onboarding agenda](https://docs.google.com/document/d/1Y2uaQCLTtV1ZyPZeoUuVHo-oJMoPlVmKlCsUcTfxf2Y/edit)

**Comment by jeremywalter** [comment]
Yeah, I think there's just no standard in the CF... which shouldn't be surprising... we just need Amanda to approve each PR for quality control and it should smooth out from here...

**Comment by ACharbonneau** [comment]
I changed it, but it is now right to the best of my knowledge

**Comment by jeremywalter** [comment]
ping

**Review by ACharbonneau — APPROVED** [review]

**Pull request merged**
